config/routes.rb
Rails.application.routes.draw do
  resources :commodities, only: %i(show), format: false
  resources :carts, only: %i(edit update), format: false
  resources :cart_commodities, only: %i(create), format: false
  devise_for :users
  root to: 'home#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_commodities, dependent: :destroy

  scope :active_cart, -> { where(ordered: 0) }

end

app/models/cart_commodity.rb
class CartCommodity < ActiveRecord::Base
  belongs_to :cart
  belongs_to :commodity
end

app/models/commodity.rb
class Commodity < ActiveRecord::Base
  scope :home_list, -> { where(view_enabled: 1).order(:position) }
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :carts, dependent: :destroy

  def active_cart
    carts.find_or_initialize_by(ordered: 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: %i(index)
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resources)
  #   user_path(current_user)
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i(email))
    # devise_parameter_sanitizer.permit(:account_update, keys: %i(name image image_cache profile))
  end
end

app/controllers/cart_commodities_controller.rb
class CartCommoditiesController < ApplicationController
  before_action :set_cart, only: %i(create)
  before_action :set_commodity, only: %i(create)

  def create
    @cart.cart_commodities.build(cart_commodity_params)
    if @cart.save
      redirect_to :back, notice: 'カートに投入しました。'
    else
      redirect_to :back, alert: 'カート投入に失敗しました。'
    end
  end

  private

  def set_cart
    @cart = current_user.active_cart
  end

  def set_commodity
    @commodity = Commodity.find(cart_commodity_params[:commodity_id])
  end

  def cart_commodity_params
    params.require(:cart_commodity).permit(:quantities, :commodity_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i(edit update)

  def edit
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  before_action :set_commodity, only: [:show, :edit, :update, :destroy]

  def index
    @commodities = Commodity.all
  end

  def show
  end

  def new
    @commodity = Commodity.new
  end

  def edit
  end

  def create
    @commodity = Commodity.new(commodity_params)

    respond_to do |format|
      if @commodity.save
        format.html { redirect_to @commodity, notice: 'Commodity was successfully created.' }
        format.json { render :show, status: :created, location: @commodity }
      else
        format.html { render :new }
        format.json { render json: @commodity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @commodity.update(commodity_params)
        format.html { redirect_to @commodity, notice: 'Commodity was successfully updated.' }
        format.json { render :show, status: :ok, location: @commodity }
      else
        format.html { render :edit }
        format.json { render json: @commodity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @commodity.destroy
    respond_to do |format|
      format.html { redirect_to commodities_url, notice: 'Commodity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_commodity
      @commodity = Commodity.find(params[:id])
    end

    def commodity_params
      params.require(:commodity).permit(:name, :price, :desctipion, :view_enabled, :position)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user, only: %i(index)
  before_action :set_commodities, only: %i(index)

  def index
  end

  private

  def set_user
    @user = current_user || User.new
  end

  def set_commodities
    @commoditites = Commodity.home_list
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_commodities_helper.rb
module CartCommoditiesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/carts/edit.html.haml
.container-fluid
  .row.m-t-1.row
    .col-xs-1
    .col-xs-8
      %p
        .h1 カート詳細
      %table.table.table-striped
        %thead
          %tr
            %th 商品名称
            %th 購入商品
            %th 削除
        %tbody
          - @cart.cart_commodities.each do |cart_commodity|
            %tr
              %td
                = cart_commodity.commodity.name
              %td
                = cart_commodity.quantities
              %td
                = '削除'
      = simple_form_for(:order, url: '', class: 'form-inline') do |f|
        .form-inputs
          = f.input :delivery_day,label: '配送日'
          = f.input :delivery_time,label: '配送時間'
          = f.input :delivery_name,label: '配送先指名'
          = f.input :delivery_address,label: '配送先住所'
          = f.input :delivery_email,label: '配送先連絡メールアドレス'
        .form-actions
          = f.button :submit, data: {disable_with: 'カート処理中...'}

app/views/commodities/show.html.haml
.container-fluid
  .row.m-t-1.row
    %p
      .h1 #{@commodity.name}
    = image_tag 'ball.png', alt: '商品画像イメージ', size: '400x400'
    %p
      %b Price:
      = @commodity.price
    %p
      %b Desctipion:
      = @commodity.desctipion
    - cart_commodity = CartCommodity.new(commodity: @commodity)
    = simple_form_for(cart_commodity, url: cart_commodities_path, class: 'form-inline') do |f|
      .form-inputs
        = f.hidden_field :commodity_id
        = f.input :quantities,label: '購入数量'
      .form-actions
        = f.button :submit, data: {disable_with: 'カート処理中...'}

app/views/home/index.html.haml
.container-fluid
  %h1.m-t-1 Sakura Market
  .row
    .col-xs-1
    .col-xs-10
      .card-deck-wrapper
        .card-deck
          - @commoditites.each do |commodity|
            .col-xs-4
              .card.card-commodity
                .card-header
                  = link_to commodity.name, commodity
                = image_tag 'ball.png', alt: '商品画像イメージ', size: '200x200'
                .card-block.card-user
                  .card-text
                .card-footer
                  = "¥ #{commodity.price}"
    .col-xs-1

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sakuramarket
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render '/shared/header'
    - if notice
      .alert.alert-success
        = notice
    - if alert
      .alert.alert-dander
        = alert
    = yield

app/views/shared/_header.html.haml
%nav.navbar.navbar-dark.bg-primary
  .navbar-brand
    = link_to 'さくらマーケット', root_path, class: 'navbar-brand'
  %ul.nav.navbar-nav.pull-xs-right
    - if user_signed_in?
      - active_cart = current_user.active_cart
      %li.nav-item
        = link_to (image_tag 'shopping_cart.png', alt: 'カート詳細画面へ', size: '40x40') , edit_cart_path(active_cart), class: 'nav-link'
      %li.nav-item
        = link_to 'カート', edit_cart_path(active_cart) , class: 'nav-link'
      -#%li.nav-item
      -#  = link_to header_user_image(current_user), edit_user_registration_path, class: 'nav-link', id: 'edit_user_header'
      %li.nav-item
        = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'
      -#%li.nav-item
      -#  = button_tag 'ツィートする', class: 'nav-link btn btn-info btn-sm',
      -#    data: {toggle: 'modal', target:'#do_tweet'}, style:'color:white;'
    - else
      %li.nav-item
        = link_to 'ログイン', new_user_session_path, class: 'nav-link', id: 'login_link_header'
      %li.nav-item
        = link_to 'アカウント作成', new_user_registration_path, class: 'nav-link', id: 'create_user_header'